### ISSUE TITLE
More information available?

### ISSUE THREAD

**Issue by GuidoNeele** [jcdickinson/AzXmpp#1]
Hi Jonathan,

Is there a webpage with more information regarding this project? I'm looking for a xmpp server running in Azure. This project came up but would like some more information if that's possible.

Thanks in advance!

Regards. 

Guido

**Comment by jcdickinson** [comment]
Sorry Guido, it was a pet project that I simply ran out of time for - I'll delete this repository to avoid any further confusion.

Give this a go: https://hub.docker.com/r/rroemhild/ejabberd/ https://azure.microsoft.com/en-us/overview/containers/
